version: "3"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    depends_on:
      - dummyapi
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml
      - ./traefik/cert:/cert:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.tls=true"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.docker.localhost`)"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.routers.portainer-secure.tls=true"

  dummyapi:
    image: golang:latest
    container_name: dummyapi
    build:
      context: ./dummyapi/
      dockerfile: Dockerfile
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.dummyapi.loadbalancer.server.port=6543"

      - "traefik.http.routers.internet.entrypoints=websecure"
      - "traefik.http.routers.internet.rule=Host(`dummyapi.docker.localhost`) && Method(`GET`)"
      - "traefik.http.routers.internet.service=dummyapi"
      - "traefik.http.routers.internet.tls=true"

      - "traefik.http.routers.local.entrypoints=dummyapi"
      - "traefik.http.routers.local.rule=Host(`dummyapi.docker.localhost`) && Method(`GET`, `POST`)"
      - "traefik.http.routers.local.service=dummyapi"
      - "traefik.http.routers.local.tls=false"

networks:
  proxy:

