http:
  middlewares:
    secureHeaders:
      headers:
        accessControlAllowHeaders:
          - Authorization
          - Origin
          - Content-Type
          - Accept
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - HEAD
        accessControlAllowOrigin: "origin-list-or-null"
        accessControlMaxAge: 100
        addVaryHeader: true
        frameDeny: true
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        referrerPolicy: same-origin
        featurePolicy: vibrate 'self'

    user-auth:
      basicAuth:
        users:
          - "testuser:$apr1$azFXf5gx$hkKVGu1gfN/Zp7DJwdhRr0" # traefik dashboard login: testuser, testpassword

tls:
  certificates:
    - certFile: /cert/testcert.crt
      keyFile: /cert/testcert.key
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /cert/testcert.crt
        keyFile: /cert/testcert.key

  options:
    default:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
          - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
        curvePreferences:
          - CurveP521
          - CurveP384

